### ISSUE TITLE
[2.52] Bug on debian (chrome and firefox)

### ISSUE THREAD

**Issue by landre3567** [sunhater/kcfinder#1]
The install works fine on a windows server but does nothing (files folder not shown) under debian.

After investigation I found the pb in /js/browser/settings.js

I had to comments 2 lines : 

//    $('#order input[value="' + _.kuki.get('order') + '"]').get(0).checked = true;

and 

//    $('#view input[value="' + _.kuki.get('view') + '"]').get(0).checked = true;

in both cases get(0) returned undefined.

Regards,

Luc

**Comment by sunhater** [comment]
please check your cookie settings first...

**Comment by ADmad** [comment]
@sunhater I am having same problem on chrome on linux. I don't think it's cookie settings issue.

**Comment by ADmad** [comment]
To clarify i am getting the javascript error when checking http://kcfinder.sunhater.com/demos/standalone and error is caused by the lines pointed out by @landre3567

**Comment by sunhater** [comment]
Okay... the demo is fixed. Incorrect cookie domain in config.php
