### ISSUE TITLE
Add custom option on right click like copy file path

### ISSUE THREAD

**Issue by gfucka** [sunhater/kcfinder#10]
Hi,
it is possibile to add custom element on the file right click??
For example I like to copy the file path on the clipboard.
Thank you

**Comment by sunhater** [comment]
In version 3.0 there is a `js/091.menus.js` file. `_.menuFile()` method generates right-click menu for files. Note that there is two menu versions (for single and multiple files). You can modify the code inserting `_.menu.addItem(url, label, callback);` at the right spot.
You should allow writable flag for the web server of `cache` directory and its content to make changes in javascript code.
