### ISSUE TITLE
Inefficiency caused by getimagesize

### ISSUE THREAD

**Issue by tomaswindsor** [sunhater/kcfinder#11]
In file core/browser.php function getFiles calls inefficient getimagesize on every file. This tends to be very slow operation for large files. As a result, displaying contents of directories that contain many large files is very slow.

An attempt to workaround the problem by filtering out non-images can be found here: http://sourceforge.net/apps/phpbb/kcfinder/viewtopic.php?f=5&t=300

In one of my projects (where directory contained many video files), I've applied that patch and the difference was significant (something like 10 seconds delay -> almost instant).

**Comment by sunhater** [comment]
In the master branch the problem is fixed (I think). You should have EXIF PHP extension.
https://github.com/sunhater/kcfinder/commit/1a498b5ae26ff23f1c7a6d83c6e22bed1621b7b5#diff-f768262c2320c8c757e824cc6c8b2e41
Could you try the current development version?

**Comment by sunhater** [comment]
Hm... I tested it but still is slow...

**Comment by sunhater** [comment]
I really want to leave image detection without pay attention on filename extension. Maybe I can limit file size, which can be detected as image.

**Comment by tomaswindsor** [comment]
My report was relevant to last released version (2.53).

I've just tested the current development version and it is still very slow. So far the patch I referenced works best for me.

Maybe you could try this as an alternative to getimagesize: https://github.com/tommoor/fastimage

**Comment by sunhater** [comment]
Thanks! I have done it to the master branch and the performance is much better.

**Comment by tomaswindsor** [comment]
I can confirm the performance is fine now.

**Comment by sunhater** [comment]
I tested on Linux server and fastImage cannot detect jpeg image. On my Windows desktop works perfectly. Reopening issue...

**Comment by sunhater** [comment]
I solved it using a forked version of FastImage: https://github.com/pinleague/fastimage
