### ISSUE TITLE
kcfinder as bower package

### ISSUE THREAD

**Issue by mikemix** [sunhater/kcfinder#111]
Please publish this excellent library as a [bower](http://bower.io) package.

It's really very easy and quick and would allow us to automatically download and update kcfinder in our applications. If you need any help, I would be very happy to assist you.

**Comment by SerbanC** [comment]
It seems it already is: http://bower.io/search/?q=kcfinder

**Comment by mikemix** [comment]
This is my package. Sorry for any inconvenience.
