### ISSUE TITLE
Upload folder created in default location when session has expired

### ISSUE THREAD

**Issue by marcovtwout** [sunhater/kcfinder#12]
Consider the following scenario:

.1. KCFinder is integrated with an external application. The session config enables KCFinder and sets the uploadDir, following the instructions (http://kcfinder.sunhater.com/integrate):

```
$_SESSION['KCFINDER'] = array();
$_SESSION['KCFINDER']['disabled'] = false;
$_SESSION['KCFINDER']['uploadURL'] = "/users/" . $user['username'] . "/upload";
$_SESSION['KCFINDER']['uploadDir'] = "";
```

.2. A user tries to access `browse.php` while the session has expired or by using a direct link.
.3. The action get stopped because config setting `disabled` defaults to true: https://github.com/sunhater/kcfinder/blob/master/core/class/browser.php#L82

However, between step 2 and 3, browser::__construct() is called, which creates the upload directory if it doesn't exist yet. Because the session config is missing, this means the upload folders (with default permissions) are created in the default location. We end up with an extra set of (bogus) folders, which in our circumstances cannot be deleted easily because of file permissions.

Could the code be modified to check `disabled` earlier in the process, or to postpone folder creation until after this check? I can imagine this problem scenario applies to other settings as well.

**Comment by sunhater** [comment]
Understood. I'll fix that.

**Comment by marcovtwout** [comment]
Excellent. :) And thank you for moving your project to GitHub and picking up development again!

**Comment by marcovtwout** [comment]
Any ETA on the fix? :)

**Comment by sunhater** [comment]
Just done. https://github.com/sunhater/kcfinder/commit/6671866f48b03e1319df49c758f527be7ffc39c5

**Comment by marcovtwout** [comment]
Thank you. :) Do you plan to publish a new (stable) release soon? Is there a changelog between 2.54 and 3.0?

**Comment by sunhater** [comment]
Here: https://github.com/sunhater/kcfinder/blob/master/doc/Changelog

**Comment by marcovtwout** [comment]
I see updating to 3.0 has a new theme engine, which we are not ready for yet. Is it possible to include this bugfix in a new 2.x release?

**Comment by sunhater** [comment]
Hm... No... I think the 3.0-dev1 is working properly. Theme & theme engine are ready! Not-ready things are below TODO marker.

**Comment by marcovtwout** [comment]
What I mean is, we have a custom theme, and we would have to put work in creating a new 3.0-compatible theme, right? We need to integrate this fix in our current production projects.

**Comment by sunhater** [comment]
Excuse me, but why I have to do this? You have custom theme, so you can customize the new one. If you want 2.x you can modify PHP code by yourself.

**Comment by marcovtwout** [comment]
I'm not saying you should do it, I am asking if you could. :) It simply depends on your release and maintainance policy, which is not defined anywhere yet. It also depends on how you view this particular issue.

I'm assuming you use semantic versioning. Since you decided to create a new major version number (3), usually other projects decide not to add new features to the old major version (2) but maintain releases for important fixes. In my eyes, this is one important fix and justifies a new 2.x release. Or are you saying you are not supporting the 2.x branch at all? After all, it -is- your current production branch..

I don't want to demand anything, just trying to figure out what your policy is. ;)

**Comment by sunhater** [comment]
The main reason there is a 2.x branch is that it supports PHP < 5.3. I don't want to maintain this deprecated branch anymore. Everyone can fork KCFinder and make his/her own modifications.

**Comment by marcovtwout** [comment]
Alright, thanks for clarifying the situation. Maybe it is smart to do a stable 3.0 release as soon as possible, and keep any non-essential features for the next release(s)? Since you don't want to maintain 2.x, you will benefit from people using the 3.x version as early as possible.

**Comment by marcovtwout** [comment]
Confirmed fix (merged patch into our 2.x code base)
