### ISSUE TITLE
Accented file names

### ISSUE THREAD

**Issue by glinseMelek** [sunhater/kcfinder#14]
When i upload a file with accented characters the file name on the server will be flawed.
For example "Nénuphars.jpg" become "NÃ©nuphars.jpg"

When i changed the return code of the uploader class normalizeFilename() to this

return utf8_encode($filename);

the file name is written in the correct format on the server but then the file explorer doesn't work anymore because i get a javascript error 

Uncaught TypeError: Cannot call method 'toLowerCase' of null 
in the file index.php line 4320

![image](https://f.cloud.github.com/assets/7057905/2523076/d576cd62-b4cb-11e3-91bc-4f18afe9af9d.png)

When i checked the json response after uploading the file or even when reload the page, i found that the name of the file "Nénuphars.jpg" is sent as null.

When i added utf8_decode in the dir class content() an error occurs at class_fastImage class

**Comment by sunhater** [comment]
I have no such problems with accent characters even without utf8_encode() change. I think it depends on your platform. Please provide detailed information about your system.

**Comment by glinseMelek** [comment]
It was tested on windows xp.
Using wamp server 2.2
php version 5.3.13
apache 2.2.22

**Comment by sunhater** [comment]
I think (your) Windows XP is not full unicode-compatible. I tested this issue on Windows 7 and Gentoo Linux and it works perfectly without any change in the code.

**Comment by glinseMelek** [comment]
I even tried hosting the script (original code from github) on linux production server on hostgator and still the accent problem persists.

**Comment by sunhater** [comment]
Well... I can't help while I have no problems.

**Comment by glinseMelek** [comment]
Just to make sure that we are on the same page, the file name in the scipt is fine, but when i view it on the server (in the windows explorer) i find the file name flawed.

**Comment by sunhater** [comment]
It seems that your filesystem is not unicode-compatible. There is a solution, that you don't like. To use `filenameChangeChars` and `dirnameChangeChars` options. For example:

``` php
    'filenameChangeChars' => array(
        'à' => "a",
        'é' => "e",
        // etc...
    ),

    'dirnameChangeChars' => array(
        'à' => "a",
        'é' => "e",
        // etc...
    ),
```

**Comment by sunhater** [comment]
http://stackoverflow.com/questions/1525830/how-do-i-use-filesystem-functions-in-php-using-utf-8-strings

**Comment by sunhater** [comment]
Hey, I added new option to the config: `_normalizeFilenames`. If you set it to `true`, all accented characters will be changed and any special characters will be removed.
It is commited to the master branch only. Soon official 3.0 varsion will be released.

**Comment by glinseMelek** [comment]
Cool update, thanks.

**Comment by 2pay** [comment]
or you can convert unicode char:

add function to kcfinder/core/class/uploader.php : 

public function get_ascii($st){
    $vietChar   = 'á|à|ả|ã|ạ|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ|é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ|ó|ò|ỏ|õ|ọ|ơ|ớ|ờ|ở|ỡ|ợ|ô|ố|ồ|ổ|ỗ|ộ|ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự|í|ì|ỉ|ĩ|ị|ý|ỳ|ỷ|ỹ|ỵ|đ|Á|À|Ả|Ã|Ạ|Ă|Ắ|Ằ|Ẳ|Ẵ|Ặ|Â|Ấ|Ầ|Ẩ|Ẫ|Ậ|É|È|Ẻ|Ẽ|Ẹ|Ê|Ế|Ề|Ể|Ễ|Ệ|Ó|Ò|Ỏ|Õ|Ọ|Ơ|Ớ|Ờ|Ở|Ỡ|Ợ|Ô|Ố|Ồ|Ổ|Ỗ|Ộ|Ú|Ù|Ủ|Ũ|Ụ|Ư|Ứ|Ừ|Ử|Ữ|Ự|Í|Ì|Ỉ|Ĩ|Ị|Ý|Ỳ|Ỷ|Ỹ|Ỵ|Đ';
    $engChar    = 'a|a|a|a|a|a|a|a|a|a|a|a|a|a|a|a|a|e|e|e|e|e|e|e|e|e|e|e|o|o|o|o|o|o|o|o|o|o|o|o|o|o|o|o|o|u|u|u|u|u|u|u|u|u|u|u|i|i|i|i|i|y|y|y|y|y|d|A|A|A|A|A|A|A|A|A|A|A|A|A|A|A|A|A|E|E|E|E|E|E|E|E|E|E|E|O|O|O|O|O|O|O|O|O|O|O|O|O|O|O|O|O|U|U|U|U|U|U|U|U|U|U|U|I|I|I|I|I|Y|Y|Y|Y|Y|D';
    $arrVietChar    = explode("|", $vietChar);
    $arrEngChar     = explode("|", $engChar);
    return str_replace($arrVietChar, $arrEngChar, $st);
}

edit in kcfinder/core/class/uploader.php : 

protected function normalizeFilename($filename) {

```
    if (isset($this->config['filenameChangeChars']) &&
        is_array($this->config['filenameChangeChars'])
    )
        $filename = strtr($filename, $this->config['filenameChangeChars']);

    if (isset($this->config['_normalizeFilenames']) && $this->config['_normalizeFilenames'])
        $filename = file::normalizeFilename($filename);

    return $this->get_ascii($filename);
}
```

and edit function Dir.
