### ISSUE TITLE
Multiple instances of KCFinder on the same page

### ISSUE THREAD

**Issue by jonybigude** [sunhater/kcfinder#18]
Hi!

I am currently using this method http://kcfinder.sunhater.com/demos/iframe to embed KCFinder on my site in order to make an simple CMS. 

I would like to call KCFinder more then once on the same site but for some reason I can't. The point here is that when I click on a button a modal pops up and KCFinder is there. It works fine with only one instance but when I add other modals KCFinder stops working. I tried to add more kcfinder_div both on javascript, html and CSS but it didn't work. I tried like this: var div = document.getElementById('kcfinder_div', 'kcfinder_div1');

I can't call the same modal for every button because every button is associated with a different image with a different description, so I really need to call the same instance or a new instance in different modals on the same page.

How do I do it?

**Comment by sunhater** [comment]
Well, I modified the code for you ;-)

``` html
<html>
<head>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<style type="text/css">
#kcfinder_div {
    position: absolute;
    width: 670px;
    height: 400px;
    background: #e0dfde;
    border: 2px solid #3687e2;
    border-radius: 6px;
    padding: 1px;
}
</style>
<script type="text/javascript">
function openKCFinder(field) {

    if ($('#kcfinder_div').get(0)) {
        $('#kcfinder_div').detach();
        return;
    }

    $(field).after('<div id="kcfinder_div"><iframe name="kcfinder_iframe" src="browse.php?type=files&dir=files/public" frameborder="0" width="100%" height="100%" marginwidth="0" marginheight="0" scrolling="no" /></div>');

    window.KCFinder = {
        callBack: function(url) {
            window.KCFinder = null;
            field.value = url;
            $('#kcfinder_div').detach();
        }
    };

}
</script>
</head>
<body>
<input type="text" readonly="readonly" value="Click here to browse the server" onclick="openKCFinder(this)" style="width:600px;cursor:pointer" /><br />
<input type="text" readonly="readonly" value="Click here to browse the server" onclick="openKCFinder(this)" style="width:600px;cursor:pointer" /><br />
</body>
</html>
```

**Comment by jonybigude** [comment]
Works like a charm! I don't know how to thank you, most of the creators of such a project would just ignore me! A million thanks! :+1:

Perhaps something to include on the next version?
