### ISSUE TITLE
Use Grunt for CSS/JS preparation

### ISSUE THREAD

**Issue by cheesypoof** [sunhater/kcfinder#29]
I'm confused by and disagree with the decision to include CSS and JS minification and concatenation functions in KCFinder 3.

In my opinion, it would be much more appropriate to do this with a task runner such as [Grunt](http://gruntjs.com/). Outside of developing KCFinder and/or a theme, the average user has no need to rebuild the CSS and JS files.

Any thoughts? I would be willing to send in a pull request for this if there is agreement on the matter. Thanks!

**Comment by sunhater** [comment]
Average user doesn't have to do anything. Developers that wish to modify the JavaScript code should change filesystem permissions in `cache` directory to be writable by the web server. And when the code is ready to be published, just set `_cssMinCmd` and `_jsMinCmd` and refresh the KCFinder.

**Comment by cheesypoof** [comment]
I think we are talking at cross-purposes here; I agree with you that the average user doesn't have to do anything. My point is that the release zip could be made smaller if source CSS/JS weren't included and minification functions stripped out.

Additionally, I believe Grunt could make the development workflow more intuitive and optimized.
