### ISSUE TITLE
"Unknown error" because of checkFilePath/realpath

### ISSUE THREAD

**Issue by Morthiras** [sunhater/kcfinder#30]
When clicking on "Refresh" in KCFinder after a clean install I get an "Unknown error".
"uploadURL" is set up like this: "http://www.example.com/kcfinder/upload"
"uploadDir" is set up like this: ""
Setting "uploadDir" to an absolute path like "/document_root/example/kcfinder/upload" doesn't help.
The error happen in line 821 in browser.php when checkFilePath() is called.
The function realpath in line 406 in uploader.php deletes the beginning of the path string of the document root, so the result of checkFilePath is always false.
For example:
document_root = /customers/homepages/12/d12345678/htdocs
$file = /customers/homepages/12/d12345678/htdocs/example/kcfinder/upload
realpath($file) = /homepages/12/d12345678/htdocs/example/kcfinder/upload

**Comment by Morthiras** [comment]
I tested an older version of KCFinder (14. Apr.) and it works fine. So the bug must've slipped in during the last couple of security fixes and folder name stuff changes.

Btw, if you do not change the standard uploadURL (upload), KCFinder trys to create the folder files and .thumbs within the KCFinder folder instaed of the uploads folder! Setting it to a full URL like http://www.example.com/kcfinder/upload circumvents this. But I think this should be looked at too.

**Comment by pBoness** [comment]
I`m having the same problem, clean install of CKeditor version 4.4.1 and a clean install of KCfinder version 3.11 (also tried version 3.10 same problem). 

I does create thumbnails in the set directory, but it won`t show me any when I click browse server.
It shows the filenames of the images. If I click on refresh I get: "Unknown Error"
When I switch from thumbnail mode to list mode and I also get "Unknown Error"

I can upload images, but it just won`t show me the thumbnails

I Installed KCfinder 2.52 and everything works again, it shows the thumbs and no Unknown error notices. 

My config.php:
$_CONFIG = array(

// GENERAL SETTINGS

```
'disabled' => true,
'uploadURL' => '../../uploads',
'uploadDir' => '../../uploads',
'theme' => "dark",
'opener' => "ckeditor",

'types' => array(

// (F)CKEditor types
    'files'   =>  "",
    'flash'   =>  "swf",
    'images'  =>  "*img",

// TinyMCE types
    'file'    =>  "",
    'media'   =>  "swf flv avi mpg mpeg qt mov wmv asf rm",
    'image'   =>  "*img",
),
```

// IMAGE SETTINGS

```
'imageDriversPriority' => "imagick gmagick gd",
'jpegQuality' => 90,
'thumbsDir' => "kcthumbs",

'maxImageWidth' => 0,
'maxImageHeight' => 0,

'thumbWidth' => 100,
'thumbHeight' => 100,

'watermark' => "",
```

// DISABLE / ENABLE SETTINGS

```
'denyZipDownload' => false,
'denyUpdateCheck' => false,
'denyExtensionRename' => false,
```

// PERMISSION SETTINGS

```
'dirPerms' => 0755,
'filePerms' => 0644,

'access' => array(

    'files' => array(
        'upload' => true,
        'delete' => true,
        'copy'   => true,
        'move'   => true,
        'rename' => true
    ),

    'dirs' => array(
        'create' => true,
        'delete' => true,
        'rename' => true
    )
),

'deniedExts' => "exe com msi bat cgi pl php phps phtml php3 php4 php5 php6 py pyc pyo pcgi pcgi3 pcgi4 pcgi5 pchi6",
```

// MISC SETTINGS

```
'filenameChangeChars' => array(/*
    ' ' => "_",
    ':' => "."
*/),

'dirnameChangeChars' => array(/*
    ' ' => "_",
    ':' => "."
*/),

'mime_magic' => "",

'cookieDomain' => "",
'cookiePath' => "",
'cookiePrefix' => 'KCFINDER_',
```

// THE FOLLOWING SETTINGS CANNOT BE OVERRIDED WITH SESSION SETTINGS

```
'_normalizeFilenames' => false,
'_check4htaccess' => true,
//'_tinyMCEPath' => "/tiny_mce",

'_sessionVar' => "KCFINDER",
//'_sessionLifetime' => 30,
//'_sessionDir' => "/full/directory/path",
//'_sessionDomain' => ".mysite.com",
//'_sessionPath' => "/my/path",

//'_cssMinCmd' => "java -jar /path/to/yuicompressor.jar --type css {file}",
//'_jsMinCmd' => "java -jar /path/to/yuicompressor.jar --type js {file}",
```

);

Anyone any idea?

**Comment by sunhater** [comment]
Can't help here while i have not access to the buggy system...

**Comment by enumag** [comment]
Well the main problem is that "Unknown error" is really hard to debug because it is thrown on many places in KCFinder without any code or anything else that could help identify the problem.

It would be nice to use exceptions instead and have a debug option which would reveal the exception type, code and message.

**Comment by iDutch** [comment]
I can also confirm Morthiras findings. Could anyone tell me what exactly the purpose of the checkFilePath function is? I would like to give it a try fixing it. For now, I changed the function so it always returns true and everything seems working now. However, I might just did something really dangerous by skipping this check.

**Comment by Gummy35** [comment]
Consider the code for checkFilePath (I remove the windows specific code):

protected function checkFilePath($file) {
        $rPath = realpath($file);
        return (substr($rPath, 0, strlen($this->typeDir)) === $this->typeDir);
    }

Now consider the following environnement :

 /mnt/projects/prod/public/medias/editor/images/
where 
/mnt/projects/prod/public/medias is in fact a symbolic link to /mnt/nfsdata/medias

given $file =  /mnt/projects/prod/public/medias/editor/images/
$rPath = /mnt/nfsdata/medias/editor/images/
$this->typeDir = /mnt/projects/prod/public/medias/editor/images/

substr($rPath, 0, strlen($this->typeDir)) = /mnt/nfsdata/medias/editor/images/

So substr... will never be equal to $this->typeDir, and checkFilePath will return false.

So, to put it plain and simple, if you use symbolic links in your path, it will fail.

**Comment by sunhater** [comment]
Thanks! I'll fix that soon!

**Comment by sunhater** [comment]
I think now it's fixed. Please test.

**Comment by DylanDavids** [comment]
Hello SunHater,

First of all, i realIy like your project.. But there still is a problem the application. I have replaced the return value of checkFilePath with true instead of (substr($rPath, 0, strlen($this->typeDir)) === $this->typeDir) so it works.. But i think that isn't the proper solution.

What to do?

Oh and i also can't delete folders..

**Comment by sunhater** [comment]
Please provide more info... Have you tested with current project tree or 3.12 version?... It's working on my test server when document root is symlink... Maybe you have defined uploadDir into your config.php pointed to a symlink...
checkFilePath checks if the path is valid. If it always returns true, the script could operate with files outside the upload folder.

**Comment by DylanDavids** [comment]
Dude, you are a genius! I didn't update my kcfinder to the new project tree. Now i did and it works like a charm! 

Keep up the good work :+1:

**Comment by setiyotio** [comment]
i have error warning unknow error when open folder and etc action in kcfinder
![report-error](https://user-images.githubusercontent.com/25787616/33251805-2cfe5d44-d36c-11e7-88e2-bd54b2b10774.png)

**Comment by setiyotio** [comment]
pliss help me sir

**Comment by enumag** [comment]
@setiyotio KCFinder is completely dead project. And from what I have seen in the source code it has serious security issues as well. Don't use it.

**Comment by setiyotio** [comment]
@enumag ok thank for info broo

**Comment by eMkoTo** [comment]
best solution for symlinks
`protected` function checkFilePath($file) {
        $symlink = dirname($this->typeDir);
        $rPath = realpath($file);
        if (strtoupper(substr(PHP_OS, 0, 3)) == "WIN"){
            $rPath = str_replace("\\", "/", $rPath);
        }
        $path = (substr($rPath, 0, strlen($this->typeDir)) === $this->typeDir);
        //fix folder is symlink
        if(!$path && is_link($symlink)){
            $path = true;
        }
        return $path;
    `}`

**Comment by dominik-j** [comment]
the above does not work for me, 
I have compared the address "/app/webroot/ img/uplo" with "../img/uploads/images" and i change to like this. Im my project is enought:

protected function checkFilePath($file) {
        $rPath = realpath($file);
        if (strtoupper(substr(PHP_OS, 0, 3)) == "WIN")
            $rPath = str_replace("\\", "/", $rPath);

        $typeDir = str_replace('../', '', $this->typeDir);
        return (strpos($rPath, $typeDir) !== false);
    }
