### ISSUE TITLE
Blank Browser

### ISSUE THREAD

**Issue by fatstar** [sunhater/kcfinder#33]
Thank you for your greate job.
I tried to use KCFinder 3.11 with CKEditor, but I got blank browse screen.
And after browse screen blanked, web browser hanged.
v. 3.11 Upload works OK.  
v. 2.54 everything works OK.
I use XAMPP with window 7, Chrome browser, CKeditor 4.4 PHP with Laravel.
Thanks

**Comment by hranicka** [comment]
Hello, I've removed these lines: https://github.com/sunhater/kcfinder/blob/master/js/050.init.js#L229-L232

And everything works fine now. Are these loops also your problem? Can you try remove them and if it solves your problems, I can create pull-request for @sunhater (don't forget on base.js file).

**Comment by sunhater** [comment]
Just removing this lines is not recommended. Anyway, I just [fixed it](https://github.com/sunhater/kcfinder/commit/bfbb10008a65bd8d1f5ddcb728e672723cae5744#diff-0eae0dfec7fe6881f9b8b1da36d94bcdL227).

**Comment by damorossi** [comment]
I had the same problem. I found a code line that goes with short tag. So change the short tag to <?php. 
Go find & replace. Search for "<?=" and change it to "<?php echo". That single thing turned me mad! 
cheers
damianrossi.com.ar
