### ISSUE TITLE
PDF files

### ISSUE THREAD

**Issue by dna75** [sunhater/kcfinder#43]
When I upload a PDF everything is fine but when I click on the link in the browser it opens a TXT file (instead of the PDF).

**Comment by sunhater** [comment]
Remove the last one, two or three lines (try all cases) in `kcfinder/core/upload.htaccess` and `.htaccess` from your upload folder.

```
SetHandler None
SetHandler default-handler
ForceType text/plain
```

It's about the security so the HTML files cannot be rendered.
