### ISSUE TITLE
KCFinder on unusual port not working

### ISSUE THREAD

**Issue by nicelife90** [sunhater/kcfinder#44]
I'm building an intranet right now and i use your soft in my cms.

To manage this intranet from outside of my work lan network i have created a port forward in my router so when i try to manage file from my home the url of KCFinder is for exemple:

http://exempledomain.com:8064/data/browse.php?lng=fr&type=files&dir=files/Politiques_Entreprise

And KCFinder is not working on port different of 80. 

This is a print screen of the result outside of my intranet. If im inside my network on port 80 everything work perfect.

![sans titre](https://cloud.githubusercontent.com/assets/1786747/3487612/d3d0c810-048e-11e4-86d4-2f4665941283.png)

Could you help me with that please.

Sorry about my English i speak french.

**Comment by sunhater** [comment]
I've tested KCFinder on various ports on my workstation changing `Listen` setting into apache config file `httpd.conf` and it worked fine.
![kcf-port](https://cloud.githubusercontent.com/assets/5509562/3487695/842a607c-0499-11e4-8c72-d2efd0007719.png)

**Comment by nicelife90** [comment]
OK I'll try to figure it out what happen on my side i think is the port forward because in reality the web server listen on port 80 and the router do NAT to transform external (wan) port 8064 to internal (lan) port 80 if i try to change port of my server to 8064 kcfinder work for me to.

But in prod mode i can't leave the listen port to 8064 and on external port 80 i have another web server for webmail. I can't use external port 80.

Thank you!

**Comment by sunhater** [comment]
I'm sorry. I can't help. I'm not sure the reason of the problem is KCFinder itself.
