### ISSUE TITLE
 dynamic permission settings for create dirs

### ISSUE THREAD

**Issue by MadeNade** [sunhater/kcfinder#46]
I need to dynamic permission settings for create dirs. example: If user is admin dirs create=> true or if user is normal create => false.

Stackoverflow issus:  http://stackoverflow.com/questions/24914899/how-to-set-dynamic-permission-settings-in-kcfinder

How Do can in create this?

**Comment by sunhater** [comment]
It's possible without any modifications. Just set $_SESSION['KCFINDER']['access'].

**Comment by MadeNade** [comment]
I add This Line : 
$_SESSION['KCFINDER']['uploadURL'] = 'http://localhost/user/uploads/files/1/';
$_SESSION['KCFINDER']['uploadDir'] = 'C:\xampp\htdocs\user\uploads\files\1';
$_SESSION['KCFINDER']['access']['dirs'] =  array(
        'create' => true
    );

Now, when click in upload i see this error: 

The address wasn't understood

Firefox doesn't know how to open this address, because one of the following protocols (kcact) isn't associated with any program or is not allowed in this context.

**Comment by sunhater** [comment]
You have to include the whole access array into the session
