### ISSUE TITLE
Class Imagick not found in lib/class_image_imagick.php

### ISSUE THREAD

**Issue by utteam** [sunhater/kcfinder#5]
I have OS X, Imagick installed, version of KCFinder downloaded via composer using tag 2.52. In said file there are multiple references to Imagick class without leading backslash which sets root namespace.

**Comment by sunhater** [comment]
Thanks for the info! I'll fix that..

2014-02-19 12:55 GMT+02:00 utteam notifications@github.com:

**Comment by utteam** [comment]
Thanks, please note that in meantime I've edited original issue. KCFinder was actually downloaded via composer using tag 2.52 if that matters.

**Comment by sunhater** [comment]
Fixed. Could you check if it's working? I have problems installing imagemagick pecl module on windows platform
