### ISSUE TITLE
No Select Button TinyMCE

### ISSUE THREAD

**Issue by angaziz** [sunhater/kcfinder#7]
Hi creator, thanks for this awesome plugin. I already integrate it with my website on textbox and there is no problemo. But I also integrate this with TinyMCE 4 but when browse from server. There is no select button or even double click to select the image is do nothing.
Why this could be happen? There's also an error said like this (dont know if this related) : GET path/to/plugins/tinymce/tiny_mce_popup.js 404 (Not Found) 

Here is the script : 
function openKCFinderTinyMCE(field_name, url, type, win) {
    tinyMCE.activeEditor.windowManager.open({
        file: 'path/to/kcfinder/browse.php?opener=tinymce&type=' + type,
        title: 'KCFinder',
        width: 700,
        height: 500,
        resizable: "yes",
        inline: true,
        close_previous: "no",
        popup_css: false
    }, {
        window: win,
        input: field_name
    });
    return false;
}

I search everywhere but there is not help. Thanks

**Comment by sunhater** [comment]
TinyMCE 4 is not supported yet

**Comment by angaziz** [comment]
Why? I use that script and it was running correctly, except the select context. Hope this work soon, it was a good web file explorer ...

**Comment by sunhater** [comment]
Okay, I added TinyMCE 4 support to the master branch. To get worked, you should specify "tinymce4" to opener GET parameter. and pass field_name. Example:

``` javascript
file: 'path/to/kcfinder/browse.php?opener=tinymce4&type=' + type + '&field=' + field_name,
```

Detailed information here: http://kcfinder.sunhater.com/integrate#tinymce4

**Comment by angaziz** [comment]
Yeah, glad to hear this. Thanks ...

**Comment by solymani** [comment]
he dear
please help me
i use tinymce in my web
also i use kcfinder for manage image and image selector
i cannot use kcfinder in tinymce by insert image and browse it to select
i dont see any button in image window

please help me
if you can send me a sample file that work true

thanks a lot
