### ISSUE TITLE
standalone

### ISSUE THREAD

**Issue by bflydesign** [sunhater/kcfinder#80]
I am looking for the code to open a standalone version on a page. Besides the demo on http://kcfinder.sunhater.com/demos/standalone I can't find any code.

**Comment by murilolobato** [comment]
How do you did that? I'm also need to put the kcfinder directly on a page

**Comment by bflydesign** [comment]
@murilolobato You have to use the full url: 

```
/kcfinder/browse.php?type=images&lang=bg&dir=images/public
```

You can e.g. open this url in a separate iFrame on your page (I know, iFrames are not done :p).

Look for the title 'Custom Integration' on http://kcfinder.sunhater.com/integrate
There you have all the GET-parameters you can add to the url to define the language, the storage directory, ...

**Comment by murilolobato** [comment]
I ended using other file browser. I had a necessity to browse files  that are not in a public directory,  for example: /home/myfiles 
I used elfinder
